### ISSUE TITLE
DetectX-Search script & policy producing false failures on subset of machines

### ISSUE THREAD

**Issue by apizz** [haircut/detectx-jamf#3]
Since we purchased DetectX Swift this summer, I had noticed that a number of machines that were running our DetectX search policy were producing policy log failures, while most were running the policy just fine.

While the policy itself is throwing failures for this subset of machines ...

![screen shot 2019-01-04 at 1 33 56 pm](https://user-images.githubusercontent.com/11789931/50704597-f44c8280-1025-11e9-8b35-d4f05de70a94.png)

... from what I can tell, the script is running fine and successfully writing to our `results.json` file.  Below is the contents of `results.json` for the machine that produced the policy error above (notice the timestamps on the email and the DetectX searchdate).

```
cat /Library/Application\ Support/JAMF/Addons/DetectX/results.json 
{
	"product" : "DetectX Swift",
	"registered" : true,
	"version" : "1.082",
	"searchdate" : "2019-01-04T08:06:37-0500",
	"duration" : 118.47,
	"spotlightindexing" : true,
	"issues" : [

	],
	"infections" : [

	]
```
This is happening both on the current DetectX version - 1.082 - and the previous version we were deploying.

When I run `sudo /Applications/Utilities/DetectX\ Swift.app/Contents/MacOS/DetectX\ Swift search -aj /Library/Application\ Support/JAMF/Addons/DetectX/results.json` manually on a couple of the machines in question, I can confirm that the exit code of the command is `0` and that data of the results.json file gets updated.  This leads me to believe it's something with the error logic of the DetectX-Search script.

The majority of our machines are on 10.13.6 and running DetectX 1.082.

If there's any additional information you need from me to troubleshoot further, please let me know.

**Comment by apizz** [comment]
Should [line 54](https://github.com/haircut/detectx-jamf/blob/master/run-detectx-search.py#L54) have the same `if true` logic as [line 72](https://github.com/haircut/detectx-jamf/blob/master/run-detectx-search.py#L72)?

**Comment by haircut** [comment]
@apizz The [latest commit](https://github.com/haircut/detectx-jamf/commit/de5202136fdbf286e230218605803f15621b6f00) resolves this issue. Please test again and close this issue if you find no issue.

**Comment by apizz** [comment]
@haircut Thanks, I will test on Monday

**Comment by apizz** [comment]
Confirmed on 2 machines that script & policy runs successfully.  Thanks for the quick fix, @haircut 🍻
